

-- ============================================================
-- HOTFIX: 2048 Master + Fruit Slice compatibility (one-argument RPCs)
-- ============================================================
create table if not exists public.game2048_leaderboard (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 username text not null default 'Player', avatar_url text not null default '🔢',
 score integer not null check(score>=0), created_at timestamptz not null default now()
);
create table if not exists public.fruit_slice_leaderboard (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 username text not null default 'Player', avatar_url text not null default '🍉',
 score integer not null check(score>=0), created_at timestamptz not null default now()
);
create unique index if not exists game2048_one_per_user on public.game2048_leaderboard(user_id);
create unique index if not exists fruit_slice_one_per_user on public.fruit_slice_leaderboard(user_id);
alter table public.game2048_leaderboard enable row level security;
alter table public.fruit_slice_leaderboard enable row level security;
grant select on public.game2048_leaderboard, public.fruit_slice_leaderboard to anon, authenticated;
drop policy if exists game2048_public_read on public.game2048_leaderboard;
create policy game2048_public_read on public.game2048_leaderboard for select to anon, authenticated using (true);
drop policy if exists fruit_slice_public_read on public.fruit_slice_leaderboard;
create policy fruit_slice_public_read on public.fruit_slice_leaderboard for select to anon, authenticated using (true);

drop function if exists public.submit_2048_score(integer,text);
drop function if exists public.submit_fruit_slice_score(integer,text);
create or replace function public.submit_2048_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/100));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>10000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then raise exception 'Profile not found'; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.game2048_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.game2048_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;
create or replace function public.submit_fruit_slice_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/50));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then raise exception 'Profile not found'; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.fruit_slice_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.fruit_slice_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;
grant execute on function public.submit_2048_score(integer), public.submit_fruit_slice_score(integer) to authenticated;
NOTIFY pgrst, 'reload schema';
