-- Snake Arena Supabase schema
-- Run this in Supabase SQL Editor.
-- Uses the current Supabase JS client with the browser-safe publishable key.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'Player',
  avatar_url text not null default '🐍',
  coins integer not null default 100 check (coins >= 0),
  high_score integer not null default 0 check (high_score >= 0),
  games_played integer not null default 0 check (games_played >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🐍',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_score_idx on public.leaderboard(score desc);
create index if not exists leaderboard_user_idx on public.leaderboard(user_id);

alter table public.profiles enable row level security;
alter table public.leaderboard enable row level security;

revoke all on table public.profiles from anon;
revoke all on table public.leaderboard from anon;
grant select, insert, update on public.profiles to authenticated;
grant select on public.leaderboard to anon, authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "leaderboard_public_read" on public.leaderboard;
create policy "leaderboard_public_read" on public.leaderboard for select to anon, authenticated
using (true);

-- Only let signed-in users insert a row for themselves.
revoke insert, update, delete on public.leaderboard from anon, authenticated;
grant insert on public.leaderboard to authenticated;

drop policy if exists "leaderboard_insert_own" on public.leaderboard;
create policy "leaderboard_insert_own" on public.leaderboard for insert to authenticated
with check ((select auth.uid()) = user_id);

-- Atomic score submission + reward function for the prototype.
-- It keeps the browser from directly changing the user's coins/high score.
create or replace function public.submit_snake_score(p_score integer)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  p public.profiles;
  reward integer := greatest(0, floor(p_score / 10));
begin
  if uid is null then
    raise exception 'Login required';
  end if;

  if p_score < 0 or p_score > 100000 then
    raise exception 'Invalid score';
  end if;

  select * into p from public.profiles where id = uid for update;

  if not found then
    insert into public.profiles(id, username, avatar_url, coins, high_score, games_played)
    values (uid, coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid), 'Player'), '🐍', 100, 0, 0)
    returning * into p;
  end if;

  update public.profiles
  set coins = coins + reward,
      high_score = greatest(high_score, p_score),
      games_played = games_played + 1,
      updated_at = now()
  where id = uid;

  insert into public.leaderboard(user_id, username, avatar_url, score)
  values (uid, p.username, p.avatar_url, p_score);

  return json_build_object('score', p_score, 'reward', reward);
end;
$$;

revoke all on function public.submit_snake_score(integer) from public, anon;
grant execute on function public.submit_snake_score(integer) to authenticated;

-- Keep updated_at fresh on profile edits.
create or replace function public.set_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute function public.set_profile_updated_at();

-- Birdy Bird addition (safe to run on an existing Snake Arena database)
create table if not exists public.birdy_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🐦',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create index if not exists birdy_leaderboard_score_idx on public.birdy_leaderboard(score desc);
alter table public.birdy_leaderboard enable row level security;
revoke all on table public.birdy_leaderboard from anon;
grant select on public.birdy_leaderboard to anon, authenticated;
grant insert on public.birdy_leaderboard to authenticated;
drop policy if exists "birdy_leaderboard_public_read" on public.birdy_leaderboard;
create policy "birdy_leaderboard_public_read" on public.birdy_leaderboard for select to anon, authenticated using (true);
drop policy if exists "birdy_leaderboard_insert_own" on public.birdy_leaderboard;
create policy "birdy_leaderboard_insert_own" on public.birdy_leaderboard for insert to authenticated with check ((select auth.uid()) = user_id);

create or replace function public.submit_birdy_score(p_score integer)
returns json language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); p public.profiles; reward integer := greatest(0, p_score * 5);
begin
  if uid is null then raise exception 'Login required'; end if;
  if p_score < 0 or p_score > 100000 then raise exception 'Invalid score'; end if;
  select * into p from public.profiles where id = uid for update;
  if not found then
    insert into public.profiles(id, username, avatar_url, coins, high_score, games_played)
    values (uid, coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid), 'Player'), '🐍', 100, 0, 0) returning * into p;
  end if;
  update public.profiles set coins = coins + reward, games_played = games_played + 1, updated_at = now() where id = uid;
  insert into public.birdy_leaderboard(user_id, username, avatar_url, score) values (uid, p.username, p.avatar_url, p_score);
  return json_build_object('score', p_score, 'reward', reward);
end; $$;
revoke all on function public.submit_birdy_score(integer) from public, anon;
grant execute on function public.submit_birdy_score(integer) to authenticated;


-- Snake Arena Phase 4 migration: Archery, Tower, Reaction Time
-- Safe to run after your existing Snake + Birdy Bird schema.

create table if not exists public.archery_leaderboard (id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,username text not null,avatar_url text not null default '🎯',score integer not null check(score>=0),created_at timestamptz not null default now());
create table if not exists public.tower_leaderboard (id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,username text not null,avatar_url text not null default '🏗️',score integer not null check(score>=0),created_at timestamptz not null default now());
create table if not exists public.reaction_leaderboard (id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,username text not null,avatar_url text not null default '⚡',score integer not null check(score>=1 and score<=10000),created_at timestamptz not null default now());

create index if not exists archery_score_idx on public.archery_leaderboard(score desc); create index if not exists tower_score_idx on public.tower_leaderboard(score desc); create index if not exists reaction_score_idx on public.reaction_leaderboard(score asc);

alter table public.archery_leaderboard enable row level security; alter table public.tower_leaderboard enable row level security; alter table public.reaction_leaderboard enable row level security;
revoke all on table public.archery_leaderboard, public.tower_leaderboard, public.reaction_leaderboard from anon; grant select on public.archery_leaderboard, public.tower_leaderboard, public.reaction_leaderboard to anon,authenticated;

create or replace function public.submit_archery_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/10)); begin if uid is null then raise exception 'Login required'; end if; if p_score<0 or p_score>100000 then raise exception 'Invalid score'; end if; select * into p from public.profiles where id=uid for update; update public.profiles set coins=coins+reward, updated_at=now() where id=uid; insert into public.archery_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score); return json_build_object('score',p_score,'reward',reward); end; $$;
create or replace function public.submit_tower_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,p_score*2); begin if uid is null then raise exception 'Login required'; end if; if p_score<0 or p_score>10000 then raise exception 'Invalid score'; end if; select * into p from public.profiles where id=uid for update; update public.profiles set coins=coins+reward, updated_at=now() where id=uid; insert into public.tower_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score); return json_build_object('score',p_score,'reward',reward); end; $$;
create or replace function public.submit_reaction_score(p_ms integer) returns json language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); p public.profiles; reward integer:=case when p_ms<300 then 10 when p_ms<500 then 5 else 3 end; begin if uid is null then raise exception 'Login required'; end if; if p_ms<1 or p_ms>10000 then raise exception 'Invalid reaction time'; end if; select * into p from public.profiles where id=uid for update; update public.profiles set coins=coins+reward, updated_at=now() where id=uid; insert into public.reaction_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_ms); return json_build_object('ms',p_ms,'reward',reward); end; $$;

revoke all on function public.submit_archery_score(integer), public.submit_tower_score(integer), public.submit_reaction_score(integer) from public,anon; grant execute on function public.submit_archery_score(integer), public.submit_tower_score(integer), public.submit_reaction_score(integer) to authenticated;

-- Public read policies
 drop policy if exists archery_public_read on public.archery_leaderboard; create policy archery_public_read on public.archery_leaderboard for select to anon,authenticated using(true);
 drop policy if exists tower_public_read on public.tower_leaderboard; create policy tower_public_read on public.tower_leaderboard for select to anon,authenticated using(true);
 drop policy if exists reaction_public_read on public.reaction_leaderboard; create policy reaction_public_read on public.reaction_leaderboard for select to anon,authenticated using(true);

-- Make each new-game leaderboard one-row-per-player and preserve the best result.
create unique index if not exists archery_one_per_user on public.archery_leaderboard(user_id);
create unique index if not exists tower_one_per_user on public.tower_leaderboard(user_id);
create unique index if not exists reaction_one_per_user on public.reaction_leaderboard(user_id);

create or replace function public.submit_archery_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/10)); begin
 if uid is null then raise exception 'Login required'; end if; if p_score<0 or p_score>100000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update; update public.profiles set coins=coins+reward,updated_at=now() where id=uid;
 insert into public.archery_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.archery_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward); end; $$;

create or replace function public.submit_tower_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,p_score*2); begin
 if uid is null then raise exception 'Login required'; end if; if p_score<0 or p_score>10000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update; update public.profiles set coins=coins+reward,updated_at=now() where id=uid;
 insert into public.tower_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.tower_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward); end; $$;

create or replace function public.submit_reaction_score(p_ms integer) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=case when p_ms<300 then 10 when p_ms<500 then 5 else 3 end; begin
 if uid is null then raise exception 'Login required'; end if; if p_ms<1 or p_ms>10000 then raise exception 'Invalid reaction time'; end if;
 select * into p from public.profiles where id=uid for update; update public.profiles set coins=coins+reward,updated_at=now() where id=uid;
 insert into public.reaction_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_ms)
 on conflict(user_id) do update set score=least(public.reaction_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('ms',p_ms,'reward',reward); end; $$;


-- Phase 6 migration: Catapult King
create table if not exists public.catapult_leaderboard (id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,username text not null,avatar_url text not null default '🏰',score integer not null check(score>=0),created_at timestamptz not null default now());
create index if not exists catapult_score_idx on public.catapult_leaderboard(score desc);
alter table public.catapult_leaderboard enable row level security;
revoke all on table public.catapult_leaderboard from anon; grant select on public.catapult_leaderboard to anon,authenticated;
drop policy if exists catapult_public_read on public.catapult_leaderboard; create policy catapult_public_read on public.catapult_leaderboard for select to anon,authenticated using(true);
create unique index if not exists catapult_one_per_user on public.catapult_leaderboard(user_id);
create or replace function public.submit_catapult_score(p_score integer) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(2,floor(p_score/80)); begin
 if uid is null then raise exception 'Login required'; end if; if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then raise exception 'Profile not found'; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.catapult_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.catapult_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward); end; $$;
revoke all on function public.submit_catapult_score(integer) from public,anon; grant execute on function public.submit_catapult_score(integer) to authenticated;


-- Snake Arena Phase 6 migration: Target Rush, Highway Rush, Brick Blast
-- Safe to run on an existing Snake Arena database.

create table if not exists public.target_rush_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🎯',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.highway_rush_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🏎️',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.brick_blast_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🧱',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists target_rush_score_idx on public.target_rush_leaderboard(score desc);
create index if not exists highway_rush_score_idx on public.highway_rush_leaderboard(score desc);
create index if not exists brick_blast_score_idx on public.brick_blast_leaderboard(score desc);

alter table public.target_rush_leaderboard enable row level security;
alter table public.highway_rush_leaderboard enable row level security;
alter table public.brick_blast_leaderboard enable row level security;

revoke all on table public.target_rush_leaderboard, public.highway_rush_leaderboard, public.brick_blast_leaderboard from anon;
grant select on public.target_rush_leaderboard, public.highway_rush_leaderboard, public.brick_blast_leaderboard to anon, authenticated;
grant insert on public.target_rush_leaderboard, public.highway_rush_leaderboard, public.brick_blast_leaderboard to authenticated;

drop policy if exists target_rush_public_read on public.target_rush_leaderboard;
create policy target_rush_public_read on public.target_rush_leaderboard for select to anon, authenticated using (true);
drop policy if exists highway_rush_public_read on public.highway_rush_leaderboard;
create policy highway_rush_public_read on public.highway_rush_leaderboard for select to anon, authenticated using (true);
drop policy if exists brick_blast_public_read on public.brick_blast_leaderboard;
create policy brick_blast_public_read on public.brick_blast_leaderboard for select to anon, authenticated using (true);

create or replace function public.submit_target_rush_score(p_score integer)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/100));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then insert into public.profiles(id,username,avatar_url,coins,high_score,games_played) values(uid,coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid),'Player'),'🐍',100,0,0) returning * into p; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.target_rush_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score);
 return json_build_object('score',p_score,'reward',reward);
end; $$;

create or replace function public.submit_highway_rush_score(p_score integer)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/75));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then insert into public.profiles(id,username,avatar_url,coins,high_score,games_played) values(uid,coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid),'Player'),'🐍',100,0,0) returning * into p; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.highway_rush_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
on conflict(user_id) do update set score=greatest(public.highway_rush_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;

create or replace function public.submit_brick_blast_score(p_score integer)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/25));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then insert into public.profiles(id,username,avatar_url,coins,high_score,games_played) values(uid,coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid),'Player'),'🐍',100,0,0) returning * into p; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.brick_blast_leaderboard(user_id,username,avatar_url,score) values(uid,p.username,p.avatar_url,p_score)
on conflict(user_id) do update set score=greatest(public.brick_blast_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;

revoke all on function public.submit_target_rush_score(integer), public.submit_highway_rush_score(integer), public.submit_brick_blast_score(integer) from public, anon;
grant execute on function public.submit_target_rush_score(integer), public.submit_highway_rush_score(integer), public.submit_brick_blast_score(integer) to authenticated;


-- ============================================================
-- Phase 7 FIX: Separate Target Rush mode leaderboards
-- Classic, Time Attack and Survival each have their own ranking.
-- Also fixes score submission from srcdoc/iframe games.
-- Run this whole file (or at minimum this migration section) in Supabase SQL Editor.
-- ============================================================

create table if not exists public.target_rush_classic_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🎯',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.target_rush_time_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '⏱️',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.target_rush_survival_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '❤️',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists target_rush_classic_score_idx on public.target_rush_classic_leaderboard(score desc);
create index if not exists target_rush_time_score_idx on public.target_rush_time_leaderboard(score desc);
create index if not exists target_rush_survival_score_idx on public.target_rush_survival_leaderboard(score desc);

alter table public.target_rush_classic_leaderboard enable row level security;
alter table public.target_rush_time_leaderboard enable row level security;
alter table public.target_rush_survival_leaderboard enable row level security;

drop policy if exists target_rush_classic_public_read on public.target_rush_classic_leaderboard;
create policy target_rush_classic_public_read on public.target_rush_classic_leaderboard
for select to anon, authenticated using (true);
drop policy if exists target_rush_time_public_read on public.target_rush_time_leaderboard;
create policy target_rush_time_public_read on public.target_rush_time_leaderboard
for select to anon, authenticated using (true);
drop policy if exists target_rush_survival_public_read on public.target_rush_survival_leaderboard;
create policy target_rush_survival_public_read on public.target_rush_survival_leaderboard
for select to anon, authenticated using (true);

create or replace function public.submit_target_rush_classic_score(p_score integer)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/100));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then
   insert into public.profiles(id,username,avatar_url,coins,high_score,games_played)
   values(uid,coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid),'Player'),'🐍',100,0,0)
   returning * into p;
 end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.target_rush_classic_leaderboard(user_id,username,avatar_url,score)
 values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.target_rush_classic_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;

create or replace function public.submit_target_rush_time_score(p_score integer)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/100));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then
   insert into public.profiles(id,username,avatar_url,coins,high_score,games_played)
   values(uid,coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid),'Player'),'🐍',100,0,0)
   returning * into p;
 end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.target_rush_time_leaderboard(user_id,username,avatar_url,score)
 values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.target_rush_time_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;

create or replace function public.submit_target_rush_survival_score(p_score integer)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/100));
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then
   insert into public.profiles(id,username,avatar_url,coins,high_score,games_played)
   values(uid,coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid),'Player'),'🐍',100,0,0)
   returning * into p;
 end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.target_rush_survival_leaderboard(user_id,username,avatar_url,score)
 values(uid,p.username,p.avatar_url,p_score)
 on conflict(user_id) do update set score=greatest(public.target_rush_survival_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url;
 return json_build_object('score',p_score,'reward',reward);
end; $$;

revoke all on function public.submit_target_rush_classic_score(integer), public.submit_target_rush_time_score(integer), public.submit_target_rush_survival_score(integer) from public, anon;
grant execute on function public.submit_target_rush_classic_score(integer), public.submit_target_rush_time_score(integer), public.submit_target_rush_survival_score(integer) to authenticated;


-- ============================================================
-- Game Arena Phase 8: 2048 Master + Fruit Slice
-- Profile photo upload + Friends
-- Safe migration for the existing Game Arena/Snake Arena database.
-- ============================================================

-- New game leaderboards
create table if not exists public.game2048_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🔢',
  score integer not null check(score >= 0 and score <= 10000000),
  mode text not null default 'classic',
  created_at timestamptz not null default now()
);
create table if not exists public.fruit_slice_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🍉',
  score integer not null check(score >= 0 and score <= 1000000),
  mode text not null default 'classic',
  created_at timestamptz not null default now()
);
create index if not exists game2048_score_idx on public.game2048_leaderboard(score desc);
create index if not exists fruit_slice_score_idx on public.fruit_slice_leaderboard(score desc);
alter table public.game2048_leaderboard enable row level security;
alter table public.fruit_slice_leaderboard enable row level security;
revoke all on table public.game2048_leaderboard, public.fruit_slice_leaderboard from anon;
grant select on public.game2048_leaderboard, public.fruit_slice_leaderboard to anon, authenticated;
drop policy if exists game2048_public_read on public.game2048_leaderboard;
create policy game2048_public_read on public.game2048_leaderboard for select to anon, authenticated using(true);
drop policy if exists fruit_slice_public_read on public.fruit_slice_leaderboard;
create policy fruit_slice_public_read on public.fruit_slice_leaderboard for select to anon, authenticated using(true);
drop index if exists game2048_one_per_user_mode;
create unique index if not exists game2048_one_per_user on public.game2048_leaderboard(user_id);
drop index if exists fruit_slice_one_per_user_mode;
create unique index if not exists fruit_slice_one_per_user on public.fruit_slice_leaderboard(user_id);

create or replace function public.submit_2048_score(p_score integer, p_mode text default 'classic')
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/100)); m text:=case when p_mode in('classic','easy','challenge') then p_mode else 'classic' end;
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>10000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then raise exception 'Profile not found'; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.game2048_leaderboard(user_id,username,avatar_url,score,mode) values(uid,p.username,p.avatar_url,p_score,m)
 on conflict(user_id) do update set score=greatest(public.game2048_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url,mode=excluded.mode;
 return json_build_object('score',p_score,'reward',reward,'mode',m);
end; $$;
create or replace function public.submit_fruit_slice_score(p_score integer, p_mode text default 'classic')
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles; reward integer:=greatest(0,floor(p_score/50)); m text:=case when p_mode in('classic','time','zen','challenge') then p_mode else 'classic' end;
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_score<0 or p_score>1000000 then raise exception 'Invalid score'; end if;
 select * into p from public.profiles where id=uid for update;
 if not found then raise exception 'Profile not found'; end if;
 update public.profiles set coins=coins+reward,games_played=games_played+1,updated_at=now() where id=uid;
 insert into public.fruit_slice_leaderboard(user_id,username,avatar_url,score,mode) values(uid,p.username,p.avatar_url,p_score,m)
 on conflict(user_id) do update set score=greatest(public.fruit_slice_leaderboard.score,excluded.score),username=excluded.username,avatar_url=excluded.avatar_url,mode=excluded.mode;
 return json_build_object('score',p_score,'reward',reward,'mode',m);
end; $$;
revoke all on function public.submit_2048_score(integer,text), public.submit_fruit_slice_score(integer,text) from public,anon;
grant execute on function public.submit_2048_score(integer,text), public.submit_fruit_slice_score(integer,text) to authenticated;

-- Profile photo storage bucket (public URLs, authenticated uploads)
insert into storage.buckets (id, name, public)
values ('avatars','avatars',true)
on conflict (id) do update set public=true;

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read" on storage.objects
for select using (bucket_id='avatars');

drop policy if exists "avatars_auth_insert_own_folder" on storage.objects;
create policy "avatars_auth_insert_own_folder" on storage.objects
for insert to authenticated
with check (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars_auth_update_own_folder" on storage.objects;
create policy "avatars_auth_update_own_folder" on storage.objects
for update to authenticated
using (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars_auth_delete_own_folder" on storage.objects;
create policy "avatars_auth_delete_own_folder" on storage.objects
for delete to authenticated
using (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Friends
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check(status in('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(requester_id <> addressee_id)
);
create unique index if not exists friend_request_pending_unique on public.friend_requests(requester_id,addressee_id) where status='pending';
create table if not exists public.friendships (
  user_id_a uuid not null references auth.users(id) on delete cascade,
  user_id_b uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id_a,user_id_b),
  check(user_id_a < user_id_b)
);
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
revoke all on table public.friend_requests, public.friendships from anon,authenticated;
grant select on public.friend_requests, public.friendships to authenticated;

create or replace function public.search_profiles(p_query text)
returns table(id uuid,username text,avatar_url text)
language sql security definer set search_path=public as $$
  select p.id,p.username,p.avatar_url
  from public.profiles p
  where length(trim(coalesce(p_query,''))) >= 2
    and p.id <> auth.uid()
    and p.username ilike '%'||trim(p_query)||'%'
  order by p.username
  limit 20;
$$;
revoke all on function public.search_profiles(text) from public,anon;
grant execute on function public.search_profiles(text) to authenticated;

create or replace function public.send_friend_request(p_friend_id uuid)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); existing_pending boolean; reverse_pending boolean;
begin
  if uid is null then raise exception 'Login required'; end if;
  if p_friend_id is null or p_friend_id=uid then raise exception 'Invalid friend'; end if;
  if not exists(select 1 from public.profiles where id=p_friend_id) then raise exception 'Player not found'; end if;
  if exists(select 1 from public.friendships where user_id_a=least(uid,p_friend_id) and user_id_b=greatest(uid,p_friend_id)) then
    return json_build_object('status','already_friends');
  end if;
  if exists(select 1 from public.friend_requests where requester_id=uid and addressee_id=p_friend_id and status='pending') then
    return json_build_object('status','already_pending');
  end if;
  if exists(select 1 from public.friend_requests where requester_id=p_friend_id and addressee_id=uid and status='pending') then
    return json_build_object('status','incoming_pending');
  end if;
  insert into public.friend_requests(requester_id,addressee_id) values(uid,p_friend_id);
  return json_build_object('status','sent');
end; $$;
revoke all on function public.send_friend_request(uuid) from public,anon;
grant execute on function public.send_friend_request(uuid) to authenticated;

create or replace function public.respond_friend_request(p_request_id bigint,p_accept boolean)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r public.friend_requests;
begin
  if uid is null then raise exception 'Login required'; end if;
  select * into r from public.friend_requests where id=p_request_id and addressee_id=uid and status='pending' for update;
  if not found then raise exception 'Request not found'; end if;
  if p_accept then
    update public.friend_requests set status='accepted',updated_at=now() where id=r.id;
    insert into public.friendships(user_id_a,user_id_b) values(least(r.requester_id,r.addressee_id),greatest(r.requester_id,r.addressee_id))
    on conflict do nothing;
    return json_build_object('status','accepted');
  else
    update public.friend_requests set status='rejected',updated_at=now() where id=r.id;
    return json_build_object('status','rejected');
  end if;
end; $$;
revoke all on function public.respond_friend_request(bigint,boolean) from public,anon;
grant execute on function public.respond_friend_request(bigint,boolean) to authenticated;

create or replace function public.list_friend_requests()
returns table(id bigint,requester_id uuid,username text,avatar_url text,created_at timestamptz)
language sql security definer set search_path=public as $$
  select r.id,r.requester_id,p.username,p.avatar_url,r.created_at
  from public.friend_requests r
  join public.profiles p on p.id=r.requester_id
  where r.addressee_id=auth.uid() and r.status='pending'
  order by r.created_at desc;
$$;
revoke all on function public.list_friend_requests() from public,anon;
grant execute on function public.list_friend_requests() to authenticated;

create or replace function public.list_friends()
returns table(id uuid,username text,avatar_url text,created_at timestamptz)
language sql security definer set search_path=public as $$
  select p.id,p.username,p.avatar_url,f.created_at
  from public.friendships f
  join public.profiles p on p.id = case when f.user_id_a=auth.uid() then f.user_id_b else f.user_id_a end
  where f.user_id_a=auth.uid() or f.user_id_b=auth.uid()
  order by p.username;
$$;
revoke all on function public.list_friends() from public,anon;
grant execute on function public.list_friends() to authenticated;

-- Keep avatars synchronized in existing public leaderboard rows after a profile photo update.
create or replace function public.sync_my_leaderboard_profile()
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles;
begin
  if uid is null then raise exception 'Login required'; end if;
  select * into p from public.profiles where id=uid;
  update public.leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.birdy_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.archery_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.tower_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.reaction_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.catapult_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.target_rush_classic_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.target_rush_time_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.target_rush_survival_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.highway_rush_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.brick_blast_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.game2048_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  update public.fruit_slice_leaderboard set username=p.username,avatar_url=p.avatar_url where user_id=uid;
  return json_build_object('status','ok');
end; $$;
revoke all on function public.sync_my_leaderboard_profile() from public,anon;
grant execute on function public.sync_my_leaderboard_profile() to authenticated;

-- Stability migration: keep one best result per player for the six external leaderboards.
-- Remove legacy duplicate rows before creating the unique per-player indexes.
delete from public.target_rush_classic_leaderboard a using public.target_rush_classic_leaderboard b where a.user_id=b.user_id and (a.score<b.score or (a.score=b.score and a.id<b.id));
delete from public.target_rush_time_leaderboard a using public.target_rush_time_leaderboard b where a.user_id=b.user_id and (a.score<b.score or (a.score=b.score and a.id<b.id));
delete from public.target_rush_survival_leaderboard a using public.target_rush_survival_leaderboard b where a.user_id=b.user_id and (a.score<b.score or (a.score=b.score and a.id<b.id));
delete from public.highway_rush_leaderboard a using public.highway_rush_leaderboard b where a.user_id=b.user_id and (a.score<b.score or (a.score=b.score and a.id<b.id));
delete from public.brick_blast_leaderboard a using public.brick_blast_leaderboard b where a.user_id=b.user_id and (a.score<b.score or (a.score=b.score and a.id<b.id));
create unique index if not exists target_rush_classic_one_per_user on public.target_rush_classic_leaderboard(user_id);
create unique index if not exists target_rush_time_one_per_user on public.target_rush_time_leaderboard(user_id);
create unique index if not exists target_rush_survival_one_per_user on public.target_rush_survival_leaderboard(user_id);
create unique index if not exists highway_rush_one_per_user on public.highway_rush_leaderboard(user_id);
create unique index if not exists brick_blast_one_per_user on public.brick_blast_leaderboard(user_id);
