-- Snake Arena Supabase schema
-- Run this in Supabase SQL Editor.
-- Uses the current Supabase JS client with the browser-safe publishable key.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'Player',
  avatar_url text not null default '🐍',
  coins integer not null default 100 check (coins >= 0),
  high_score integer not null default 0 check (high_score >= 0),
  games_played integer not null default 0 check (games_played >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text not null default '🐍',
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_score_idx on public.leaderboard(score desc);
create index if not exists leaderboard_user_idx on public.leaderboard(user_id);

alter table public.profiles enable row level security;
alter table public.leaderboard enable row level security;

revoke all on table public.profiles from anon;
revoke all on table public.leaderboard from anon;
grant select, insert, update on public.profiles to authenticated;
grant select on public.leaderboard to anon, authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "leaderboard_public_read" on public.leaderboard;
create policy "leaderboard_public_read" on public.leaderboard for select to anon, authenticated
using (true);

-- Only let signed-in users insert a row for themselves.
revoke insert, update, delete on public.leaderboard from anon, authenticated;
grant insert on public.leaderboard to authenticated;

drop policy if exists "leaderboard_insert_own" on public.leaderboard;
create policy "leaderboard_insert_own" on public.leaderboard for insert to authenticated
with check ((select auth.uid()) = user_id);

-- Atomic score submission + reward function for the prototype.
-- It keeps the browser from directly changing the user's coins/high score.
create or replace function public.submit_snake_score(p_score integer)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  p public.profiles;
  reward integer := greatest(0, floor(p_score / 10));
begin
  if uid is null then
    raise exception 'Login required';
  end if;

  if p_score < 0 or p_score > 100000 then
    raise exception 'Invalid score';
  end if;

  select * into p from public.profiles where id = uid for update;

  if not found then
    insert into public.profiles(id, username, avatar_url, coins, high_score, games_played)
    values (uid, coalesce((select raw_user_meta_data->>'username' from auth.users where id=uid), 'Player'), '🐍', 100, 0, 0)
    returning * into p;
  end if;

  update public.profiles
  set coins = coins + reward,
      high_score = greatest(high_score, p_score),
      games_played = games_played + 1,
      updated_at = now()
  where id = uid;

  insert into public.leaderboard(user_id, username, avatar_url, score)
  values (uid, p.username, p.avatar_url, p_score);

  return json_build_object('score', p_score, 'reward', reward);
end;
$$;

revoke all on function public.submit_snake_score(integer) from public, anon;
grant execute on function public.submit_snake_score(integer) to authenticated;

-- Keep updated_at fresh on profile edits.
create or replace function public.set_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute function public.set_profile_updated_at();